name: Bug Report
description: Let us know about an unexpected error, a crash, or an incorrect behavior.
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for taking the time to fill out this bug report.
        
        The [grayjay-android](https://github.com/futo-org/grayjay-android) issue tracker is reserved for issues relating to the Grayjay Android Application

        For general usage questions, please see: [The Official FUTO Grayjay Zulip Channel](https://chat.futo.org/#narrow/stream/46-Grayjay)

        ## If your issue is related to:
        
        * **Grayjay Official Youtube Plugin**: Open an issue at [grayjay-plugin-youtube](https://github.com/futo-org/grayjay-plugin-youtube/issues).
        * **Grayjay Official BiliBili Plugin**: Open an issue at [grayjay-plugin-bilibili](https://github.com/futo-org/grayjay-plugin-bilibili/issues).
        * **Grayjay Official Twitch Plugin**: Open an issue at [grayjay-plugin-twitch](https://github.com/futo-org/grayjay-plugin-twitch/issues).
        * **Grayjay Official Odysee Plugin**: Open an issue at [grayjay-plugin-odysee](https://github.com/futo-org/grayjay-plugin-odysee/issues).
        * **Grayjay Official Rumble Plugin**: Open an issue at [grayjay-plugin-rumble](https://github.com/futo-org/grayjay-plugin-rumble/issues).
        * **Grayjay Official Kick Plugin**: Open an issue at [grayjay-plugin-kick](https://github.com/futo-org/grayjay-plugin-kick/issues).
        * **Grayjay Official PeerTube Plugin**: Open an issue at [grayjay-plugin-peertube](https://github.com/futo-org/grayjay-plugin-peertube/issues).
        * **Grayjay Official Patreon Plugin**: Open an issue at [grayjay-plugin-patreon](https://github.com/futo-org/grayjay-plugin-patreon/issues).
        * **Grayjay Official Nebula Plugin**: Open an issue at [grayjay-plugin-nebula](https://github.com/futo-org/grayjay-plugin-nebula/issues).
        * **Grayjay Official SoundCloud Plugin**: Open an issue at [grayjay-plugin-soundcloud](https://github.com/futo-org/grayjay-plugin-soundcloud/issues).
        * **A Grayjay Unofficial Plugin**: Please open an issue in the plugin's own repository, which can be found by selecting Sources > Plugin Name > Script URL OR Repository URL.

        ## Filing a bug report

        To fix your issues faster, we need clear reproduction cases - ideally allowing us to make it happen locally. 
        * Please include all needed context. For example, Device, OS, Application, your Grayjay Configurations and Plugin versioning info.
        * if you've found out a particular series of UI interactions can introduce buggy behavior, please label those steps 1-n with markdown
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: grayjay-version
    attributes:
      label: Grayjay Version
      description: In the application, select More > Settings, scroll to the bottom and locate the value next to "Version Name".
      render: shell
      placeholder: "242"
    validations:
      required: true

  - type: dropdown
    id: plugin
    attributes:
      label: What plugins are you seeing the problem on?
      multiple: true
      options:
        - All
        - Youtube
        - BiliBili (CN)
        - Twitch (Beta)
        - Odysee
        - Rumble
        - Kick (Beta)
        - PeerTube
        - Patreon
        - Nebula (Beta)
        - SoundCloud
        - Other
    validations:
      required: true

  - type: dropdown
    id: login
    attributes:
      label: Are you experiencing the issue when logged in?
      multiple: false
      options:
        - "Yes"
        - "No"
        - N/A
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
