name: Bug Report
description: Let us know about an unexpected error, a crash, or an incorrect behavior.
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for taking the time to fill out this bug report.
        
        The [grayjay-android](https://github.com/futo-org/grayjay-android) issue tracker is reserved for issues relating to the Grayjay Android Application

        For general usage questions, please see: [The Official FUTO Grayjay Zulip Channel](https://chat.futo.org/#narrow/stream/46-Grayjay)

        ## Filing a bug report

        To fix your issues faster, we need clear reproduction cases - ideally allowing us to make it happen locally. 
        * Please include all needed context. For example, Device, OS, Application, your Grayjay Configurations and Plugin versioning info.
        * if you've found out a particular series of UI interactions can introduce buggy behavior, please label those steps 1-n with markdown

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: grayjay-version
    attributes:
      label: Grayjay Version
      description: In the application, select More > Settings, scroll to the bottom and locate the value next to "Version Name".
      render: shell
      placeholder: "242"
    validations:
      required: true

  - type: dropdown
    id: plugin
    attributes:
      label: What plugins are you seeing the problem on?
      multiple: true
      options:
        - All
        - Youtube
        - BiliBili (CN)
        - Twitch (Beta)
        - Odysee
        - Rumble
        - Kick (Beta)
        - PeerTube
        - Patreon
        - Nebula (Beta)
        - SoundCloud
        - Other
    validations:
      required: true

  - type: dropdown
    id: login
    attributes:
      label: Are you experiencing the issue when logged in?
      multiple: false
      options:
        - "Yes"
        - "No"
        - N/A
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell