blank_issues_enabled: false
contact_links:
  - name: Grayjay Troubleshooting and Feature Requests
    url: https://support.hashicorp.com/hc/en-us/requests/new
    about: For issues and feature requests related to a lost license, inability to purchase a license through FUTO Pay, please submit a support request in [The Official FUTO Grayjay Zulip Channel](https://chat.futo.org/#narrow/stream/46-Grayjay)
  - name: Offical Plugin Feedback and Questions
    url: https://chat.futo.org/#narrow/stream/46-Grayjay
    about: The Youtube Plugin has its own repository, any provider related issues or questions should be directed there.
  - name: Other Plugin-related Feedback and Questions
    url: https://github.com/futo-org/grayjay-plugin-youtube/issues
    about: Each plugin (e.g. YouTube, PeerTube, Twitch etc.) has their own repository, any provider related issues or questions should be directed to the appropriate issue tracker linked from the application.
  - name: Plugin Building, Usage, or other Questions
    url: https://chat.futo.org/#narrow/stream/46-Grayjay
    about: Please ask and answer plugin development related questions through the Grayjay Community Chat.